

mv croppedLogOFF_output_file_histos_Hist_heleTheta.pdf 1_ele.pdf
mv croppedLogOFF_output_file_histos_Hist_hproTheta.pdf 2_pro.pdf
mv croppedLogOFF_Double_output_file_histos_Hist_hproThetaFD.pdf 3_pro.pdf

mv croppedLogOFF_output_file_histos_Hist_heleproTheta.pdf 4_elepro.pdf
mv croppedLogOFF_output_file_histos_Hist_heleproThetaDVMP.pdf 5_eleproDVMP.pdf
mv croppedLogOFF_output_file_histos_Hist_LeptHadAngle.pdf 6_lephadangle.pdf

mv croppedLogON_output_file_histos_Hist_heleproTheta.pdf 7_eleproLOG.pdf
mv croppedLogON_output_file_histos_Hist_heleproThetaDVMP.pdf 8_eleproDVMPLOG.pdf
mv croppedLogOFF_output_file_histos_Hist_hproThetaCD.pdf 9_proCD.pdf
mv croppedLogOFF_output_file_histos_Hist_hproThetaFD.pdf 99_proFD.pdf
